### ISSUE TITLE
bug on actions_modmass.class.php preventing to mass edit Dolibarr invoice line extrafields 

### ISSUE THREAD

**Issue by jacmart** [jere63fr/dolibarr.modmass#1]
Great useful module however : 
Line 73 variable array_option is misspelled into array_option**s**, therefore not updating extrafields on invoice lines.

// Extrafields
						...
						$array_option = $extrafieldsline->getOptionalsFromPost($extralabelsline,$line->rowid);
						
						$result = ...   $array_options, ...;

**Comment by jere63fr** [comment]
done
